##################### redis #####################
redis: 
  sentinel:
    master: hph-master
    nodes: stl1.retail:25379,stl2.retail:25379,stl3.retail:25379
  maxRedirections: 6
  timeout: 60000
  password: foobared
  max-active: 500
  max-idle: 5000
  max-wait: 10000
  testOnBorrow: true
  expire: 3600



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
# product jdbc config
product:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.60.115:3306/hxd_product?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
      username: hxd_product_user
      password: r4BVkJkijDrNz4bt
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT user()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      filters: stat,wall,config,log4j

##################### Auto pager plugin  #####################
pagehelper:
   helperDialect: mysql
   offsetAsPageNum: true
   reasonable: false
   supportMethodsArguments: true
   params: count=countSql
   
########品牌logo上传图片 所在cdn地址########  
domain: http://cdn.winhxd.com

##################### 数据源配置在文件服务器上 #####################
jdbc:
  url: file:/opt/www/configs/spring_cloud/jdbc-mysql.properties

