spring: 
  application: 
    name: user-service   
#  zipkin:
#    serviceId: zipkin-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.60.3:1433;DatabaseName=CRM_RETAIL_UAT
    username: Retail_Uat
    password: T4wYGypz#(9::/Mq
    

eureka: 
  client: 
    healthcheck: 
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
    instance:
      lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）
  instance:
    metadata-map:
        cluster: MAIN
        
#关闭节点状态访问安全验证,生产环境要开启
management: 
  security: 
    enabled: false
    
##################### redis #####################
redis: 
  sentinel:
    master: hph-master
    nodes: stl1.retail:25379,stl2.retail:25379,stl3.retail:25379
  maxRedirections: 6
  timeout: 60000
  password: foobared
  max-active: 500
  max-idle: 5000
  max-wait: 10000
  testOnBorrow: true
  expire: 3600

# 设置熔断超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000 
  
##################### MQ #####################
#spring: 
#  activemq: 
#    broker-url: 指定ActiveMQ broker的URL，默认自动生成.
#    in-memory: 是否是内存模式，默认为true.
#    password: 指定broker的密码.
#    pooled: 是否创建PooledConnectionFactory，而非ConnectionFactory，默认false
#    user: 指定broker的用户.
  
#############token#############
token:
  expiration:
    time: 2592000




############# 业务配置 #############
# 短信
sms:
# 验证码
  code:
# 过期秒数
    expireSeconds: 300


#############  ej  ##########
registryCenter:
  serverList: zk1.retail:2181,zk2.retail:2181,zk3.retail:2181
  namespace: hxd-job-user

simpleJob:
  shardingTotalCount: 1
  shardingItemParameters: 0=hxd
  ##################shiro############