redis:
  sentinel:
    master: redis-master
    nodes: 192.168.60.102:25379
  maxRedirections: 6
  timeout: 60000
  password: foobared
  max-active: 500
  max-idle: 5000
  max-wait: 10000
  testOnBorrow: true
  expire: 3600
  
 
# product jdbc config
product:
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.60.115:3306/hxd_product?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
      username: hxd_product_user
      password: r4BVkJkijDrNz4bt
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT user()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      connection-properties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      filters: stat,wall,config,log4j
    # \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762sql\u65E0\u6CD5\u7EDF\u8BA1\uFF0C'wall'\u7528\u4E8E\u9632\u706B\u5899   

##################### Auto pager plugin  #####################
pagehelper:
   helperDialect: mysql
   offsetAsPageNum: true
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql


##################### cas #####################
cas: 
  server: 
    url: http://192.168.60.241:8080
  client: 
    url: http://localhost:3998
    
########品牌logo上传图片 所在cdn地址########  
domain: http://cdn.winhxd.com