spring: 
  application: 
    name: product-platform
  #定义一致时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
# 上传文件大小限制
  http:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB

eureka: 
  client:
    healthcheck: 
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
    instance:
      lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）
      
# 设置熔断超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

#关闭节点状态访问安全验证,生产环境要开启
# POST / refresh可动态刷新配置
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
    
##################### redis #####################
redis: 
  sentinel:
    master: redis-master
    nodes: 192.168.60.102:25379
  maxRedirections: 6
  timeout: 60000
  password: foobared
  max-active: 500
  max-idle: 5000
  max-wait: 10000
  testOnBorrow: true
  expire: 3600
  
##################### cas #####################
cas: 
  server: 
    url: http://192.168.60.241:8080
  client: 
    url: http://localhost:6333
  
########shiro session 过期时间########
shiro:
  globalSessionTimeout: 1800000
########品牌logo上传图片 所在cdn地址########  
domain: http://cdn.winhxd.com
