spring:
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
  mvc:
    locale: zh
  sleuth:
    sampler:
      probability: 0.0
  zipkin:
    sender:
      type: rabbit
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 180000
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        shutdown: /shut/down/server
  endpoint:
    shutdown:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    registry-fetch-interval-seconds: 5