spring:
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        shutdown: /shut/down/server
  endpoint:
    shutdown:
      enabled: true

#eureka注册中心首页默认跳转到各服务的swagger-ui页面
eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
