spring:
  boot:
    admin:
      client:
        instance:
          prefer-ip: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    time-zone: GMT+8
  sleuth:
    sampler:
      probability: 0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        shutdown: /shut/down/server
  endpoint:
    shutdown:
      enabled: true
