spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/admin/
        instance:
          prefer-ip: true
  zipkin:
    sender:
      type: rabbit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: retail2C_user
    password: tNB9gLJ42hwguHLK
    url: jdbc:mysql://192.168.60.115:3306/retail2C?useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
# 云平台REST服务配置
RETAIL-REST-SERVICE:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://172.18.3.35:8080/
# 缓存配置
redis:
  cluster:
    jedisClusterNode: 192.168.60.241:47000,192.168.60.241:47001,192.168.60.241:47002,192.168.60.241:47003,192.168.60.241:47004,192.168.60.241:47005
    maxTotal: 500
    maxIdle: 5000
    maxWaitMillis: 10000
    testOnBorrow: true

# 消息队列配置
mq:
  normal:
    address: 192.168.60.250:5672
    username: guest
    password: guest
    virtual-host: /
  zipkin:
    address: 192.168.60.250:5672
    username: guest
    password: guest
    virtual-host: /

#eureka注册中心首页默认跳转到各服务的swagger-ui页面
eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html