spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/admin/
        instance:
          prefer-ip: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: retail2C_user
    password: tNB9gLJ42hwguHLK
    url: jdbc:mysql://192.168.60.115:3306/retail2C?useSSL=false

# 缓存配置
redis:
  cluster:
    jedisClusterNode: 192.168.60.241:7000,192.168.60.241:7001,192.168.60.241:7002,192.168.60.241:7003,192.168.60.241:7004,192.168.60.241:7005
    maxTotal: 500
    maxIdle: 5000
    maxWaitMillis: 10000
    testOnBorrow: true