spring:
  boot:
    admin:
      client:
        instance:
          prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        shutdown: /hxd/shutdown
  endpoint:
    shutdown:
      enabled: true